Changes to move the offset commit behaviour
redpanda-data/openmessaging-benchmark pull request #37
Opened 2022-10-05 13:01 UTC by tmgstevens

Changes to move the offset commit behaviour back closer to the default behaviour, but also to avoid flooding the Kafka client with async commits. At the very least this will only submit async requests once the previous async request has come back.

New behaviour:
We're only going to submit an async commit request if:

- autoCommit is disabled AND
- there are offsets to commit AND
  - offsetCommitLingerMs is zero (the default, so no waiting for async callbacks at all) OR
  - we've waited lingerMs milliseconds since the last callback completed (+ve or -ve)

2022-10-11 18:00 UTC, travisdowns requested changes
See inline comments.

2022-10-11 18:10 UTC, tmgstevens commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +                            - offsetCommitLingerMs is zero (the default, so no waiting for async callbacks at all) OR
I agree, -1 makes more sense for the old (fire as soon as possible) way of working, 0 would then be fire as soon as the callback is complete. I'll make that change now.

2022-10-11 18:10 UTC, tmgstevens commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +    private final String OFFSET_COMMIT_CONFIG = "offsetCommitLingerMs";
Fixed

2022-10-11 18:12 UTC, tmgstevens commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +        this.autoCommit = Boolean.valueOf((String)consumerConfig.getOrDefault(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,"false"));
If `auto.commit` is not set it'll default to `false` which is the legacy behaviour (this bit came from upstream so I'm loathe to change it).

2022-10-11 18:23 UTC, travisdowns commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +        this.autoCommit = Boolean.valueOf((String)consumerConfig.getOrDefault(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,"false"));
Yeah I saw this in upstream, but it definitely seems wrong unless I'm misunderstanding something.

If you prefer not to change it, I'll at least file a bug with upstream to track it. Let me check if it is specified in every existing YAML file.

2022-10-11 18:24 UTC, tmgstevens commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +    public void onComplete(Map<TopicPartition, OffsetAndMetadata> map, Exception e) {
Done

2022-10-11 18:24 UTC, tmgstevens commented
Hi @travisdowns , I've updated per your comments.

2022-10-11 18:26 UTC, travisdowns commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +        this.autoCommit = Boolean.valueOf((String)consumerConfig.getOrDefault(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,"false"));
> If auto.commit is not set it'll default to false which is the legacy behaviour (this bit came from upstream so I'm loathe to change it).

Just to be clear though. If auto.commit is not set, then `this.autoCommit` will be set to `false` but _actually_ auto.commit is enabled in the client and happening at runtime. So `this.autoCommit` is inconsistent with the true value and so the associated logic goes the wrong thing (double commit). At least that's what I'm saying. Do you agree?

2022-10-12 11:08 UTC, tmgstevens commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +        this.autoCommit = Boolean.valueOf((String)consumerConfig.getOrDefault(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,"false"));
yes, definitely agree. It looks as though they worked around that by explicitly setting `auto.commit` to `false` in  all of the drivers, but that's not the right way to do things. I've updated the code now and we should propose all of this PR upstream ASAP IMHO.

2022-10-12 16:49 UTC, rystsov commented on driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
> +    public void onComplete(Map<TopicPartition, OffsetAndMetadata> map, Exception e) {
We need to extend OMB to keep statistics from a BenchmarkConsumer implementation, it's probably out of scope of this PR so I've created an issue to track it there https://github.com/redpanda-data/openmessaging-benchmark/issues/41

2022-10-12 18:11 UTC, travisdowns approved these changes

2022-10-12 18:13 UTC, merged